LOTTO_MIN_NUMBER = 1
LOTTO_MAX_NUMBER = 45
LOTTO_PICK_COUNT = 6

RANK_FIRST = "1등"
RANK_SECOND = "2등"
RANK_THIRD = "3등"
RANK_FOURTH = "4등"
RANK_FIFTH = "5등"
RANK_NONE = "낙첨"

RANK_CHOICES = [
    (RANK_FIRST, RANK_FIRST),
    (RANK_SECOND, RANK_SECOND),
    (RANK_THIRD, RANK_THIRD),
    (RANK_FOURTH, RANK_FOURTH),
    (RANK_FIFTH, RANK_FIFTH),
    (RANK_NONE, RANK_NONE),
]
